language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy asanjaata96/reverseproxy:v5
  - docker tag udagram-api-user asanjaata96/udagram-api-user:v5
  - docker tag udagram-api-feed asanjaata96/udagram-api-feed:v5
  - docker tag udagram-frontend:local asanjaata96/udagram-frontend:v5

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push asanjaata96/reverseproxy:v5
  - docker push asanjaata96/udagram-api-user:v5
  - docker push asanjaata96/udagram-api-feed:v5
  - docker push asanjaata96/udagram-frontend:v5
