apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: asanjaata96/udagram-api-user:v6
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"   
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: postgres-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws"
            readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret