apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: asanjaata96/udagram-api-feed:v3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: postgres-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws"
            readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret